name: Pre-commit CI

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        id: py
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ steps.py.outputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit on changed files
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/${{ github.base_ref }}...${{ github.sha }})
          else
            CHANGED_FILES=$(git diff --name-only --diff-filter=d HEAD~1)
          fi
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changed files: $CHANGED_FILES"
            pre-commit run --files $CHANGED_FILES
          else
            echo "No changed files to check."
          fi
