name: Main

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pwd
          ls -la $HOME
          echo $PATH
          command -v dotnet || echo 'dotnet not found'
      - uses: ./.github/actions/action-setup
        id: action-setup
        with:
          version: "8.0.408"
      - run: |
          pwd
          ls -la $HOME
          echo $PATH
          command -v dotnet || echo 'dotnet not found'
