name: Main

on:
  push:
    # branches:
    #   - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate artifact
        run: |
          date > updated.log
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: updated-log
          path: updated.log
      - name: List artifacts of current run
        uses: actions/github-script@v7
        with:
          script: |
            // const run_id = process.env.GITHUB_RUN_ID;
            // const { data: artifacts } = await github.rest.actions.listArtifactsForWorkflowRun({
            //   owner: context.repo.owner,
            //   repo: context.repo.repo,
            //   run_id: run_id
            // });
            const artifacts = await github.paginate(
              github.rest.actions.listWorkflowRunArtifacts,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId,
                per_page: 100,
              },
              // res => res.data.artifacts
            );
            console.log("Artifacts for this run:");
            console.log(artifacts);
            console.log(context.runId);
            const artifactNames = artifacts.map(a => a.name).join(", ");
            core.notice(`Found ${artifacts.length} artifacts: ${artifactNames}.`);
            for (const artifact of artifacts) {
              console.log(`- ${artifact.name} (id: ${artifact.id})`);
            }
