name: Main

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.408"
      # - uses: ./.github/actions/action-setup
      #   id: action-setup
      #   with:
      #     version: "8.0.408"
      - run: |
          pwd
          ls -la $HOME
          echo $PATH
          dotnet --version || echo 'dotnet not found'
          dotnet tool install -g microsoft.sqlpackage
          sqlpackage /Version
